- name: pull kubeadm config imgs
  shell: sudo kubeadm config images pull

- name: initialize the cluster
  shell: sudo kubeadm init --pod-network-cidr=10.10.0.0/16 >> cluster_initialized.txt
  args:
    chdir: $HOME
    creates: cluster_initialized.txt

- name: create .kube dir
  shell: mkdir -p $HOME/.kube

- name: copy adm conf
  shell: sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config

- name: change owner
  shell: sudo chown $(id -u):$(id -g) $HOME/.kube/config

- name: configure calico
  shell: kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.26.1/manifests/tigera-operator.yaml

- name: get custom resources
  shell: curl https://raw.githubusercontent.com/projectcalico/calico/v3.26.1/manifests/custom-resources.yaml -O

- name: Replace CIDR in custom-resources.yaml
  ansible.builtin.shell:
    cmd: "sed -i 's/cidr: 192\\.168\\.0\\.0\\/16/cidr: 10.10.0.0\\/16/g' custom-resources.yaml"

- name: apply modified resources 
  shell: kubectl create -f custom-resources.yaml